### ISSUE TITLE
Segment file does not cover all of EXE-3

### ISSUE THREAD

**Issue by joakimrydberg** [USEPE-SesarJU/bluesky#23]
It seems like the segments we have do not fully cover the area studied in Exercise 3.
I have found it a little bit difficult to figure out the exact areas mapped, but it does seem that at least the northern corners of our area is out of bounds.

The area we use is defined by:
lat_min = 52.412274
lat_max = 52.466148
lon_min = 9.638119
lon_max = 9.745655

Related
- #21

**Comment by Kara-Ro** [comment]
When you’re initializing the object “segmentationService(region)”, the only parameter it needs is the name of the region. Now, you probably submitting “Hannover,” but if you want to have more than the inner city you need to submit “Region Hannover.” It takes the region string and gets the geometry from Openstreetmap. 

If you require different method of specifying an area it needs to be implemented. 

For now I made the change to initialize the segmentationService with region="Region Hannover".
